package sh.wu.james.example.dto;

public enum HelloworldStatus {
	NEW, SUBMIT, ACCEPT, REFUSE, REJECT, CANCEL, INVESTED, INVEST_FAILURE, CERTIFYING, CERITFY_SUCCESS, CERTIFY_REFUSE, CERTIFY_REJECT, CERTIFY_TIMEMOUT, CERTIFY_CANCEL
}
